
import { SecurityService, Language } from './types';
import { 
  Target, Scale, ClipboardCheck, Cloud, Package, Bot, Gavel, AlertTriangle, Terminal, Cpu, Globe, Mail, Fingerprint, Lock, ShieldAlert, Key, UserCheck, Search
} from 'lucide-react';

export const getServices = (lang: Language): SecurityService[] => {
  const isEs = lang === 'es';
  return [
    {
      id: 'pt-01',
      title: isEs ? 'Pruebas de Penetración' : 'Penetration Testing',
      description: isEs ? 'Ciberataques simulados avanzados para identificar vulnerabilidades.' : 'Advanced simulated cyberattacks to identify vulnerabilities.',
      icon: Target,
      category: 'proactive',
      longDescription: isEs ? 'Nuestros hackers éticos realizan exploraciones profundas de su infraestructura, imitando vectores de ataque del mundo real.' : 'Our ethical hackers perform deep-dive explorations of your infrastructure, mimicking real-world attack vectors.',
      features: isEs ? ['Apps Web', 'Redes', 'Móvil', 'Ingeniería Social'] : ['Web Apps', 'Networks', 'Mobile', 'Social Engineering']
    },
    {
      id: 'nist-01',
      title: isEs ? 'Implementación NIST CSF' : 'NIST CSF Implementation',
      description: isEs ? 'Alineación completa con el Marco de Ciberseguridad NIST 2.0.' : 'Full alignment with the NIST 2.0 Cybersecurity Framework.',
      icon: Scale,
      category: 'nist',
      longDescription: isEs ? 'Establecemos un programa de ciberseguridad basado en riesgos utilizando los cinco pilares de NIST.' : 'We establish a risk-based cybersecurity program using the five NIST pillars.',
      features: ['Identify', 'Protect', 'Detect', 'Respond', 'Recover']
    },
    {
      id: 'nist-02',
      title: isEs ? 'Auditoría de Cumplimiento' : 'Compliance Audit',
      description: isEs ? 'Evaluaciones de brechas y preparación para auditorías gubernamentales.' : 'Gap assessments and readiness for government audits.',
      icon: ClipboardCheck,
      category: 'nist',
      longDescription: isEs ? 'Evaluamos sus controles actuales frente a los requisitos de NIST 800-53 o 800-171.' : 'We evaluate your current controls against NIST 800-53 or 800-171 requirements.',
      features: isEs ? ['Mapa de Controles', 'Análisis de Brechas', 'Plan de Acción'] : ['Control Mapping', 'Gap Analysis', 'POAM Development']
    },
    {
      id: 'cloud-01',
      title: isEs ? 'Seguridad AWS & Azure' : 'AWS & Azure Security',
      description: isEs ? 'Configuración de seguridad nativa y endurecimiento de IAM.' : 'Native security configuration and IAM hardening.',
      icon: Cloud,
      category: 'cloud',
      longDescription: isEs ? 'Protegemos sus cargas de trabajo en la nube mediante configuraciones seguras y monitoreo continuo.' : 'We protect your cloud workloads through secure configurations and continuous monitoring.',
      features: ['IAM Policy Review', 'VPC Hardening', 'S3 Encryption', 'GuardDuty Ops']
    },
    {
      id: 'cloud-02',
      title: isEs ? 'Seguridad de Kubernetes' : 'Kubernetes Security',
      description: isEs ? 'Blindaje de contenedores y microservicios en la nube.' : 'Shielding containers and microservices in the cloud.',
      icon: Package,
      category: 'cloud',
      longDescription: isEs ? 'Implementamos seguridad en todo el ciclo de vida del contenedor, desde la imagen hasta la ejecución.' : 'We implement security throughout the container lifecycle, from image to runtime.',
      features: ['RBAC Config', 'Network Policies', 'Image Scanning', 'Runtime Protection']
    },
    {
      id: 'ai-01',
      title: isEs ? 'Defensa de LLM' : 'LLM Defense',
      description: isEs ? 'Protección contra inyección de prompts y fuga de datos.' : 'Protection against prompt injection and data leakage.',
      icon: Bot,
      category: 'ai',
      longDescription: isEs ? 'Aseguramos que sus modelos de lenguaje no sean manipulados ni filtren información confidencial.' : 'We ensure your language models are not manipulated and do not leak confidential information.',
      features: isEs ? ['Prompt Filtering', 'Data Sanitization', 'Adversarial Testing', 'PII Detection'] : ['Prompt Filtering', 'Data Sanitization', 'Adversarial Testing', 'PII Detection']
    },
    {
      id: 'ai-02',
      title: isEs ? 'Gobernanza de IA' : 'AI Governance',
      description: isEs ? 'Políticas y ética para el despliegue seguro de IA.' : 'Policies and ethics for secure AI deployment.',
      icon: Gavel,
      category: 'ai',
      longDescription: isEs ? 'Marco de trabajo para el uso responsable y seguro de la inteligencia artificial corporativa.' : 'Framework for the responsible and secure use of corporate artificial intelligence.',
      features: isEs ? ['Ética de IA', 'Privacidad de Datos', 'Cumplimiento Legal'] : ['AI Ethics', 'Data Privacy', 'Legal Compliance']
    },
    {
       id: 'ir-01',
       title: isEs ? 'Respuesta a Incidentes' : 'Incident Response',
       description: isEs ? 'Respuesta rápida 24/7 para contener amenazas activas.' : 'Rapid 24/7 response to contain active threats.',
       icon: AlertTriangle,
       category: 'reactive',
       longDescription: isEs ? 'Nuestro equipo de élite se despliega para neutralizar amenazas y restaurar la integridad del sistema.' : 'Our elite team deploys to neutralize threats and restore system integrity.',
       features: isEs ? ['Forense Digital', 'Remediación', 'Cacería de Amenazas'] : ['Digital Forensics', 'Remediation', 'Threat Hunting']
    },
    {
      id: 'linux-01',
      title: isEs ? 'Linux Hardening (SUSE)' : 'Linux Hardening (SUSE)',
      description: isEs ? 'Blindaje experto para SUSE Linux Enterprise y virtualización segura.' : 'Expert shielding for SUSE Linux Enterprise and secure virtualization.',
      icon: Terminal,
      category: 'linux',
      longDescription: isEs ? 'Especialistas en endurecimiento de SUSE Linux Enterprise (SLES), configuración de DNS recursivo seguro y migración de infraestructuras críticas desde entornos comerciales como VMware y Hyper-V.' : 'Specialists in SUSE Linux Enterprise (SLES) hardening, secure recursive DNS configuration, and critical infrastructure migration from commercial environments like VMware and Hyper-V.',
      features: isEs ? ['Hardening SUSE SLES', 'DNS recursivo DNSSEC', 'Migración VMware/Hyper-V', 'Virtualización KVM/Xen'] : ['SUSE SLES Hardening', 'DNSSEC Recursive DNS', 'VMware/Hyper-V Migration', 'KVM/Xen Virtualization']
    },
    {
      id: 'dns-01',
      title: isEs ? 'Protección DNS Proactiva' : 'Proactive DNS Protection',
      description: isEs ? 'Defensa contra secuestro de dominios y envenenamiento de caché.' : 'Defense against domain hijacking and cache poisoning.',
      icon: Globe,
      category: 'dns',
      longDescription: isEs ? 'Blindamos su infraestructura de resolución de nombres con DNSSEC, firewalls DNS y monitoreo de integridad de zona.' : 'We shield your name resolution infrastructure with DNSSEC, DNS firewalls, and zone integrity monitoring.',
      features: isEs ? ['DNSSEC Dinámico', 'Mitigación DDoS DNS', 'Filtrado de Dominios', 'Auditoría de Registros'] : ['Dynamic DNSSEC', 'DNS DDoS Mitigation', 'Domain Filtering', 'Record Auditing']
    },
    {
      id: 'email-01',
      title: isEs ? 'Blindaje de Correo' : 'Email Shielding',
      description: isEs ? 'Defensa avanzada contra phishing, malware y fuga de datos.' : 'Advanced defense against phishing, malware, and data leakage.',
      icon: Mail,
      category: 'email',
      longDescription: isEs ? 'Implementación de gateways de correo seguros, políticas DMARC/SPF/DKIM y análisis neural de adjuntos.' : 'Implementation of secure email gateways, DMARC/SPF/DKIM policies, and neural attachment analysis.',
      features: isEs ? ['Anti-Phishing IA', 'DMARC Enforcement', 'Cifrado de Extremo a Extremo', 'Sandboxing de Adjuntos'] : ['AI Anti-Phishing', 'DMARC Enforcement', 'End-to-End Encryption', 'Attachment Sandboxing']
    },
    {
      id: 'id-01',
      title: isEs ? 'Gestión de Identidad (IAM)' : 'Identity Management (IAM)',
      description: isEs ? 'Arquitectura Zero Trust y control de acceso adaptativo.' : 'Zero Trust architecture and adaptive access control.',
      icon: Fingerprint,
      category: 'identity',
      longDescription: isEs ? 'Protegemos el perímetro de identidad mediante MFA robusto, Single Sign-On (SSO) y análisis de comportamiento de usuario.' : 'We protect the identity perimeter through robust MFA, Single Sign-On (SSO), and user behavior analytics.',
      features: isEs ? ['MFA Biométrico', 'SSO Centralizado', 'Privileged Access Mgmt', 'Zero Trust Network Access'] : ['Biometric MFA', 'Centralized SSO', 'Privileged Access Mgmt', 'Zero Trust Network Access']
    }
  ];
};

export const TRANSLATIONS = {
  es: {
    heroTitle: 'CYBERSEGURIDAD',
    heroFuture: 'AVANZADA',
    heroDesc: 'Servicios de Cyberseguridad Avanzada con integraciones de IA preventiva para una protección total de infraestructuras críticas.',
    slogan: 'Digital AI Security for Business Resilience and Profitability',
    aboutTitle: 'Líderes con Experiencia',
    aboutDesc: 'Somos una empresa con más de 20 años de experiencia en ciberseguridad, comprometida con la excelencia técnica y la protección de activos globales.',
    missionTitle: 'Misión',
    missionDesc: 'Proveer Soluciones Avanzadas de Ciberseguridad para cualquier tamaño de empresa, garantizando la continuidad del negocio mediante tecnología de vanguardia.',
    visionTitle: 'Visión',
    visionDesc: 'Crear un ecosistema más seguro y rentable para desarrollarnos plenamente en una era de transformación digital acelerada.',
    valuesTitle: 'Valores',
    valuesList: ['Innovación Constante', 'Integridad Absoluta', 'Resiliencia Operativa', 'Rentabilidad Sostenible'],
    experienceYears: '20+ Años',
    experienceText: 'Trayectoria Protegiendo el Futuro',
    btnAI: 'Obtener Escaneo IA',
    btnServices: 'Explorar Servicios',
    btnLearnMore: 'Saber Más',
    btnRequestQuote: 'Solicitar Cotización',
    quoteSuccess: '¡Solicitud enviada! Nuestro equipo se pondrá en contacto pronto.',
    socTitle: 'Centro de Operaciones (SOC)',
    socLive: 'MONITOREO EN TIEMPO REAL',
    statThreat: 'Mitigación de Amenazas',
    statResponse: 'Tiempo de Respuesta',
    statGuard: 'Guardia Activa',
    navHome: 'Inicio',
    navServices: 'Servicios',
    navAdvisor: 'Asesor IA',
    navMonitor: 'Monitor Vivo',
    navNIST: 'Marco NIST',
    navCloud: 'Seguridad Nube',
    navAI: 'Seguridad IA',
    navLinux: 'Linux Hardening',
    navDNS: 'Seguridad DNS',
    navEmail: 'Seguridad Email',
    navIdentity: 'Seguridad Identidad',
    login: 'Acceso Clientes',
    footerDesc: 'Protección especializada para activos digitales e infraestructura crítica.',
    legal: 'Legal',
    contact: 'Contacto',
    rights: 'TODOS LOS DERECHOS CIFRADOS',
    nistTitle: 'Ciberseguridad NIST 2.0',
    nistDesc: 'Marco de trabajo estándar de la industria para gestionar y reducir el riesgo de ciberseguridad.',
    cloudTitle: 'Ecosistema de Seguridad Nube',
    cloudDesc: 'Protección profunda para infraestructuras distribuidas y arquitecturas serverless.',
    aiTitle: 'Blindaje para Inteligencia Artificial',
    aiDesc: 'Estrategias de defensa para la nueva frontera de las amenazas automatizadas.',
    linuxTitle: 'The Linux Hardening (SUSE)',
    linuxDesc: 'Servicios especializados en SUSE Linux, DNS seguro y migración de virtualización propietaria.',
    dnsTitle: 'Seguridad DNS & Perímetro',
    dnsDesc: 'Blindaje de la capa de resolución para prevenir ataques de redirección y exfiltración.',
    emailTitle: 'Defensa de Mensajería Crítica',
    emailDesc: 'Protección total para el vector de ataque más explotado: el correo electrónico.',
    identityTitle: 'Identidad & Zero Trust',
    identityDesc: 'Asegurando que solo las personas correctas accedan a los recursos correctos.',
    initDeployment: 'Iniciar Despliegue',
    requestInfo: 'Solicitar Información'
  },
  en: {
    heroTitle: 'ADVANCED',
    heroFuture: 'CYBERSECURITY',
    heroDesc: 'Advanced Cybersecurity Services with preventive AI integrations for total protection of critical infrastructures.',
    slogan: 'Digital AI Security for Business Resilience and Profitability',
    aboutTitle: 'Experienced Leaders',
    aboutDesc: 'We are a company with over 20 years of experience in cybersecurity, committed to technical excellence and the protection of global assets.',
    missionTitle: 'Mission',
    missionDesc: 'To provide Advanced Cybersecurity Solutions for businesses of any size, ensuring business continuity through cutting-edge technology.',
    visionTitle: 'Vision',
    visionDesc: 'To create a safer and more profitable ecosystem to fully thrive in an era of accelerated digital transformation.',
    valuesTitle: 'Values',
    valuesList: ['Constant Innovation', 'Absolute Integrity', 'Operational Resilience', 'Sustainable Profitability'],
    experienceYears: '20+ Years',
    experienceText: 'Protective Legacy for the Future',
    btnAI: 'Get AI Scan',
    btnServices: 'Explore Services',
    btnLearnMore: 'Learn More',
    btnRequestQuote: 'Request Quote',
    quoteSuccess: 'Request sent! Our team will contact you shortly.',
    socTitle: 'Operations Center (SOC)',
    socLive: 'REAL-TIME SYSTEMS MONITORING',
    statThreat: 'Threat Mitigation',
    statResponse: 'Response Time',
    statGuard: 'Active Guard',
    navHome: 'Home',
    navServices: 'Services',
    navAdvisor: 'AI Advisor',
    navMonitor: 'Live Monitor',
    navNIST: 'NIST Framework',
    navCloud: 'Cloud Security',
    navAI: 'AI Security',
    navLinux: 'Linux Hardening',
    navDNS: 'DNS Security',
    navEmail: 'Email Security',
    navIdentity: 'Identity Security',
    login: 'Client Login',
    footerDesc: 'Specialized protection for digital assets and critical infrastructure.',
    legal: 'Legal',
    contact: 'Contact',
    rights: 'ALL RIGHTS ENCRYPTED',
    nistTitle: 'NIST 2.0 Cybersecurity',
    nistDesc: 'Industry standard framework for managing and reducing cybersecurity risk.',
    cloudTitle: 'Cloud Security Ecosystem',
    cloudDesc: 'Deep protection for distributed infrastructures and serverless architectures.',
    aiTitle: 'Artificial Intelligence Shielding',
    aiDesc: 'Defense strategies for the new frontier of automated threats.',
    linuxTitle: 'The Linux Hardening (SUSE)',
    linuxDesc: 'Specialized services in SUSE Linux, secure DNS, and proprietary virtualization migration.',
    dnsTitle: 'DNS & Perimeter Security',
    dnsDesc: 'Shielding the resolution layer to prevent redirection and exfiltration attacks.',
    emailTitle: 'Critical Messaging Defense',
    emailDesc: 'Total protection for the most exploited attack vector: email.',
    identityTitle: 'Identity & Zero Trust',
    identityDesc: 'Ensuring only the right people access the right resources.',
    initDeployment: 'Initiate Deployment',
    requestInfo: 'Request Information'
  }
};
