
import { SecurityService, Language } from './types';
import { 
  Target, Scale, ClipboardCheck, Cloud, Package, Bot, Gavel, AlertTriangle, Terminal, Cpu, Globe, Mail, Fingerprint, Lock, ShieldAlert, Key, UserCheck, Search, Network, Server, Smartphone
} from 'lucide-react';

export const getServices = (lang: Language): SecurityService[] => {
  const isEs = lang === 'es';
  return [
    {
      id: 'pt-01',
      title: isEs ? 'Pruebas de Penetración' : 'Penetration Testing',
      description: isEs ? 'Ciberataques simulados avanzados para identificar vulnerabilidades.' : 'Advanced simulated cyberattacks to identify vulnerabilities.',
      icon: Target,
      category: 'proactive',
      longDescription: isEs ? 'Nuestros hackers éticos realizan exploraciones profundas de su infraestructura, imitando vectores de ataque del mundo real.' : 'Our ethical hackers perform deep-dive explorations of your infrastructure, mimicking real-world attack vectors.',
      features: isEs ? ['Apps Web', 'Redes', 'Móvil', 'Ingeniería Social'] : ['Web Apps', 'Networks', 'Mobile', 'Social Engineering']
    },
    {
      id: 'nist-01',
      title: isEs ? 'Implementación NIST CSF' : 'NIST CSF Implementation',
      description: isEs ? 'Alineación completa con el Marco de Ciberseguridad NIST 2.0.' : 'Full alignment with the NIST 2.0 Cybersecurity Framework.',
      icon: Scale,
      category: 'nist',
      longDescription: isEs ? 'Establecemos un programa de ciberseguridad basado en riesgos utilizando los cinco pilares de NIST.' : 'We establish a risk-based cybersecurity program using the five NIST pillars.',
      features: ['Identify', 'Protect', 'Detect', 'Respond', 'Recover']
    },
    {
      id: 'net-01',
      title: isEs ? 'Defensa de Redes (NGFW)' : 'Networking Defense (NGFW)',
      description: isEs ? 'Segmentación de red avanzada y firewalls de próxima generación.' : 'Advanced network segmentation and next-generation firewalls.',
      icon: Network,
      category: 'networking',
      longDescription: isEs ? 'Protegemos su infraestructura de red mediante microsegmentación lógica y firewalls de alto rendimiento con inspección profunda de paquetes.' : 'We protect your network infrastructure via logical microsegmentation and high-performance firewalls with deep packet inspection.',
      features: isEs ? ['Microsegmentación', 'IPS de Red', 'VPN Site-to-Site', 'Filtrado L7'] : ['Microsegmentation', 'Network IPS', 'Site-to-Site VPN', 'L7 Filtering']
    },
    {
      id: 'srv-01',
      title: isEs ? 'Hardening de Servidores' : 'Server Hardening',
      description: isEs ? 'Endurecimiento extremo para entornos de producción y bases de datos.' : 'Extreme hardening for production environments and databases.',
      icon: Server,
      category: 'servers',
      longDescription: isEs ? 'Blindaje de sistemas operativos para eliminar vectores de ataque innecesarios y asegurar la integridad del kernel y servicios core.' : 'OS hardening to eliminate unnecessary attack vectors and ensure the integrity of the kernel and core services.',
      features: isEs ? ['Kernel Hardening', 'Auditd Config', 'FIM Monitoring', 'HIDS'] : ['Kernel Hardening', 'Auditd Config', 'FIM Monitoring', 'HIDS']
    },
    {
      id: 'end-01',
      title: isEs ? 'Protección de Endpoints' : 'Endpoint Protection',
      description: isEs ? 'EDR avanzado para la protección de dispositivos finales y fuerza remota.' : 'Advanced EDR for the protection of end-user devices and remote workforce.',
      icon: Smartphone,
      category: 'endpoints',
      longDescription: isEs ? 'Desplegamos agentes inteligentes de detección y respuesta (EDR/XDR) para neutralizar ransomware y amenazas avanzadas directamente en el dispositivo.' : 'We deploy intelligent detection and response agents (EDR/XDR) to neutralize ransomware and advanced threats directly on the device.',
      features: isEs ? ['Detección de Ransomware', 'Remote Wipe', 'Análisis de Memoria', 'USB Control'] : ['Ransomware Detection', 'Remote Wipe', 'Memory Analysis', 'USB Control']
    },
    {
      id: 'linux-01',
      title: isEs ? 'Linux Hardening (SUSE)' : 'Linux Hardening (SUSE)',
      description: isEs ? 'Blindaje experto para SUSE Linux Enterprise y virtualización segura.' : 'Expert shielding for SUSE Linux Enterprise and secure virtualization.',
      icon: Terminal,
      category: 'linux',
      longDescription: isEs ? 'Especialistas en endurecimiento de SUSE Linux Enterprise (SLES) y migración de infraestructuras críticas desde entornos como VMware.' : 'Specialists in SUSE Linux Enterprise (SLES) hardening and critical infrastructure migration from environments like VMware.',
      features: isEs ? ['Hardening SUSE SLES', 'DNS recursivo DNSSEC', 'Migración VMware', 'Virtualización KVM'] : ['SUSE SLES Hardening', 'DNSSEC Recursive DNS', 'VMware Migration', 'KVM Virtualization']
    },
    {
      id: 'dns-01',
      title: isEs ? 'Protección DNS Proactiva' : 'Proactive DNS Protection',
      description: isEs ? 'Defensa contra secuestro de dominios y envenenamiento de caché.' : 'Defense against domain hijacking and cache poisoning.',
      icon: Globe,
      category: 'dns',
      longDescription: isEs ? 'Blindamos su infraestructura de resolución de nombres con DNSSEC y firewalls DNS.' : 'We shield your name resolution infrastructure with DNSSEC and DNS firewalls.',
      features: isEs ? ['DNSSEC Dinámico', 'Mitigación DDoS DNS', 'Filtrado de Dominios'] : ['Dynamic DNSSEC', 'DNS DDoS Mitigation', 'Domain Filtering']
    },
    {
      id: 'email-01',
      title: isEs ? 'Blindaje de Correo' : 'Email Shielding',
      description: isEs ? 'Defensa avanzada contra phishing, malware y fuga de datos.' : 'Advanced defense against phishing, malware, and data leakage.',
      icon: Mail,
      category: 'email',
      longDescription: isEs ? 'Implementación de gateways de correo seguros y políticas DMARC/SPF/DKIM.' : 'Implementation of secure email gateways and DMARC/SPF/DKIM policies.',
      features: isEs ? ['Anti-Phishing IA', 'DMARC Enforcement', 'Cifrado de Extremo a Extremo'] : ['AI Anti-Phishing', 'DMARC Enforcement', 'End-to-End Encryption']
    },
    {
      id: 'id-01',
      title: isEs ? 'Gestión de Identidad (IAM)' : 'Identity Management (IAM)',
      description: isEs ? 'Arquitectura Zero Trust y control de acceso adaptativo.' : 'Zero Trust architecture and adaptive access control.',
      icon: Fingerprint,
      category: 'identity',
      longDescription: isEs ? 'Protegemos el perímetro de identidad mediante MFA robusto y Single Sign-On (SSO).' : 'We protect the identity perimeter through robust MFA and Single Sign-On (SSO).',
      features: isEs ? ['MFA Biométrico', 'SSO Centralizado', 'Privileged Access Mgmt'] : ['Biometric MFA', 'Centralized SSO', 'Privileged Access Mgmt']
    },
    {
      id: 'cloud-01',
      title: isEs ? 'Seguridad AWS & Azure' : 'AWS & Azure Security',
      description: isEs ? 'Configuración de seguridad nativa y endurecimiento de IAM.' : 'Native security configuration and IAM hardening.',
      icon: Cloud,
      category: 'cloud',
      longDescription: isEs ? 'Protegemos sus cargas de trabajo en la nube mediante configuraciones seguras y monitoreo de postura.' : 'We protect your cloud workloads through secure configurations and posture monitoring.',
      features: ['IAM Policy Review', 'VPC Hardening', 'S3 Encryption']
    },
    {
      id: 'ai-01',
      title: isEs ? 'Defensa de LLM' : 'LLM Defense',
      description: isEs ? 'Protección contra inyección de prompts y fuga de datos.' : 'Protection against prompt injection and data leakage.',
      icon: Bot,
      category: 'ai',
      longDescription: isEs ? 'Aseguramos que sus modelos de lenguaje no sean manipulados ni filtren información sensible.' : 'We ensure your language models are not manipulated or leak sensitive information.',
      features: ['Prompt Filtering', 'Data Sanitization', 'Adversarial Testing']
    }
  ];
};

export const TRANSLATIONS = {
  es: {
    heroTitle: 'CYBERSEGURIDAD',
    heroFuture: 'AVANZADA',
    heroDesc: 'Servicios de Cyberseguridad Avanzada con integraciones de IA preventiva para una protección total de infraestructuras críticas.',
    slogan: 'Digital AI Security for Business Resilience and Profitability',
    aboutTitle: 'Líderes con Experiencia',
    aboutDesc: 'Somos una empresa con más de 20 años de experiencia en ciberseguridad, comprometida con la excelencia técnica y la protección de activos globales.',
    missionTitle: 'Misión',
    missionDesc: 'Proveer Soluciones Avanzadas de Ciberseguridad para cualquier tamaño de empresa, garantizando la continuidad del negocio mediante tecnología de vanguardia.',
    visionTitle: 'Visión',
    visionDesc: 'Crear un ecosistema más seguro y rentable para desarrollarnos plenamente en una era de transformación digital acelerada.',
    valuesTitle: 'Valores',
    valuesList: ['Innovación Constante', 'Integridad Absoluta', 'Resiliencia Operativa', 'Rentabilidad Sostenible'],
    experienceYears: '20+ Años',
    experienceText: 'Trayectoria Protegiendo el Futuro',
    btnAI: 'Obtener Escaneo IA',
    btnServices: 'Explorar Servicios',
    btnLearnMore: 'Saber Más',
    btnRequestQuote: 'Solicitar Cotización',
    quoteSuccess: '¡Solicitud enviada! Nuestro equipo se pondrá en contacto pronto.',
    socTitle: 'Centro de Operaciones (SOC)',
    socLive: 'MONITOREO EN TIEMPO REAL',
    statThreat: 'Mitigación de Amenazas',
    statResponse: 'Tiempo de Respuesta',
    statGuard: 'Guardia Activa',
    navHome: 'Inicio',
    navServices: 'Servicios',
    navAdvisor: 'Asesor IA',
    navMonitor: 'Monitor Vivo',
    navNIST: 'Marco NIST',
    navCloud: 'Seguridad Nube',
    navAI: 'Seguridad IA',
    navLinux: 'Linux Hardening',
    navDNS: 'Seguridad DNS',
    navEmail: 'Seguridad Email',
    navIdentity: 'Seguridad Identidad',
    navNetworking: 'Seguridad Redes',
    navServers: 'Seguridad Servidores',
    navEndpoints: 'Seguridad Endpoints',
    login: 'Acceso Clientes',
    footerDesc: 'Protección especializada para activos digitales e infraestructura crítica.',
    legal: 'Legal',
    contact: 'Contacto',
    rights: 'TODOS LOS DERECHOS CIFRADOS',
    nistTitle: 'Ciberseguridad NIST 2.0',
    nistDesc: 'Marco de trabajo estándar de la industria para gestionar y reducir el riesgo de ciberseguridad.',
    cloudTitle: 'Ecosistema de Seguridad Nube',
    cloudDesc: 'Protección profunda para infraestructuras distribuidas y arquitecturas serverless.',
    aiTitle: 'Blindaje para Inteligencia Artificial',
    aiDesc: 'Estrategias de defensa para la nueva frontera de las amenazas automatizadas.',
    linuxTitle: 'The Linux Hardening (SUSE)',
    linuxDesc: 'Servicios especializados en SUSE Linux, DNS seguro y migración de virtualización propietaria.',
    dnsTitle: 'Seguridad DNS & Perímetro',
    dnsDesc: 'Blindaje de la capa de resolución para prevenir ataques de redirección y exfiltración.',
    emailTitle: 'Defensa de Mensajería Crítica',
    emailDesc: 'Protección total para el vector de ataque más explotado: el correo electrónico.',
    identityTitle: 'Identidad & Zero Trust',
    identityDesc: 'Asegurando que solo las personas correctas accedan a los recursos correctos.',
    networkingTitle: 'Defensa de Redes Críticas',
    networkingDesc: 'Blindaje de la capa de transporte y segmentación lógica de activos empresariales.',
    serversTitle: 'Hardening de Servidores',
    serversDesc: 'Endurecimiento extremo para entornos de producción y bases de datos.',
    endpointsTitle: 'Protección de Dispositivos',
    endpointsDesc: 'Seguridad total para la fuerza de trabajo remota y dispositivos móviles.',
    initDeployment: 'Iniciar Despliegue',
    requestInfo: 'Solicitar Información'
  },
  en: {
    heroTitle: 'ADVANCED',
    heroFuture: 'CYBERSECURITY',
    heroDesc: 'Advanced Cybersecurity Services with preventive AI integrations for total protection of critical infrastructures.',
    slogan: 'Digital AI Security for Business Resilience and Profitability',
    aboutTitle: 'Experienced Leaders',
    aboutDesc: 'We are a company with over 20 years of experience in cybersecurity, committed to technical excellence and the protection of global assets.',
    missionTitle: 'Mission',
    missionDesc: 'To provide Advanced Cybersecurity Solutions for businesses of any size, ensuring business continuity through cutting-edge technology.',
    visionTitle: 'Vision',
    visionDesc: 'To create a safer and more profitable ecosystem to fully thrive in an era of accelerated digital transformation.',
    valuesTitle: 'Values',
    valuesList: ['Constant Innovation', 'Absolute Integrity', 'Operational Resilience', 'Sustainable Profitability'],
    experienceYears: '20+ Years',
    experienceText: 'Protective Legacy for the Future',
    btnAI: 'Get AI Scan',
    btnServices: 'Explore Services',
    btnLearnMore: 'Learn More',
    btnRequestQuote: 'Request Quote',
    quoteSuccess: 'Request sent! Our team will contact you shortly.',
    socTitle: 'Operations Center (SOC)',
    socLive: 'REAL-TIME SYSTEMS MONITORING',
    statThreat: 'Threat Mitigation',
    statResponse: 'Response Time',
    statGuard: 'Active Guard',
    navHome: 'Home',
    navServices: 'Services',
    navAdvisor: 'AI Advisor',
    navMonitor: 'Live Monitor',
    navNIST: 'NIST Framework',
    navCloud: 'Cloud Security',
    navAI: 'AI Security',
    navLinux: 'Linux Hardening',
    navDNS: 'DNS Security',
    navEmail: 'Email Security',
    navIdentity: 'Identity Security',
    navNetworking: 'Networking Security',
    navServers: 'Server Security',
    navEndpoints: 'Endpoint Security',
    login: 'Client Login',
    footerDesc: 'Specialized protection for digital assets and critical infrastructure.',
    legal: 'Legal',
    contact: 'Contact',
    rights: 'ALL RIGHTS ENCRYPTED',
    nistTitle: 'NIST 2.0 Cybersecurity',
    nistDesc: 'Industry standard framework for managing and reducing cybersecurity risk.',
    cloudTitle: 'Cloud Security Ecosystem',
    cloudDesc: 'Deep protection for distributed infrastructures and serverless architectures.',
    aiTitle: 'Artificial Intelligence Shielding',
    aiDesc: 'Defense strategies for the new frontier of automated threats.',
    linuxTitle: 'The Linux Hardening (SUSE)',
    linuxDesc: 'Specialized services in SUSE Linux, secure DNS, and proprietary virtualization migration.',
    dnsTitle: 'DNS & Perimeter Security',
    dnsDesc: 'Shielding the resolution layer to prevent redirection and exfiltration attacks.',
    emailTitle: 'Critical Messaging Defense',
    emailDesc: 'Total protection for the most exploited attack vector: email.',
    identityTitle: 'Identity & Zero Trust',
    identityDesc: 'Ensuring only the right people access the right resources.',
    networkingTitle: 'Critical Network Defense',
    networkingDesc: 'Shielding the transport layer and logical segmentation of corporate assets.',
    serversTitle: 'Server Hardening',
    serversDesc: 'Extreme hardening for production environments and databases.',
    endpointsTitle: 'Device Protection',
    endpointsDesc: 'Total security for remote workforce and mobile devices.',
    initDeployment: 'Initiate Deployment',
    requestInfo: 'Request Information'
  }
};
